#需要使用的配置文件
spring:
 profiles:
  active: prod


#family:
# family-name: "happy family"
# father: "Jack"
# mother: "Rose"
# child: "Tom"
# years: ${random.int(4,20)}


person:
 name: "zhangsan"
 age: 23
 happy: false
 birthday: 2003/01/15
 maps: {k1:v1;k2:v2}
 lists:
  - code
  - girl
  - music
 dog:
  name: "多多"
  age: ${random.int(2,11)}